/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniM */

#ifndef _Included_JniM
#define _Included_JniM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniM
 * Method:    sayRunPlace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniM_sayRunPlace
  (JNIEnv *, jobject);

/*
 * Class:     JniM
 * Method:    getKeyCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JniM_getKeyCode
  (JNIEnv *, jobject);

/*
 * Class:     JniM
 * Method:    showPanel
 * Signature: ([[Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_JniM_showPanel
  (JNIEnv *, jobject, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
